# Generated by Django 4.0.4 on 2022-07-04 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('module', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quiz', '0001_initial'),
        ('completion', '0001_initial'),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completion',
            name='modules',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='module.module'),
        ),
        migrations.AddField(
            model_name='completion',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.page'),
        ),
        migrations.AddField(
            model_name='completion',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.quizzes'),
        ),
        migrations.AddField(
            model_name='completion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
