# Generated by Django 4.0.4 on 2022-07-04 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('completion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='completed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='completion',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='classroom.course'),
        ),
        migrations.AlterField(
            model_name='completion',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
